name: Deploy to UBA-DEV

on:
  push:
    branches:
      - main

jobs:
  Deploy_on_UBA_DEV:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: UBA-DEV  
    steps:
      - name: Deploy Stack via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            if [ -f .env ]; then
              rm .env
            fi
            echo '${{ secrets.DEV_ENV }}' > .env
            ls -ltra
            ./deploy.sh
